name: bookia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
