name: bookia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  device_preview: ^1.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  go_router: ^16.2.1
  lottie: ^3.1.2
  pinput: ^5.0.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  flutter_xlider: ^3.5.0
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
